djangotest/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from first_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^first_app/', include('first_app.urls')),
    url(r'^$', views.index, name='index')
]

first_app/urls.py
from django.conf.urls import url
from first_app import views

app_name = 'first_app'

urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^Register$', views.signup_view, name='register'),

    url(r'^Login$', views.login_view, name='login'),

    url(r'^Logout$', views.logout_view, name='logout'),

    url(r'^Donate$', views.donate_view, name='donate'),

    url(r'^Donate2$', views.donate2_view, name='donate2'),

    url(r'^Donate3$', views.donate3_view, name='donate3'),

    url(r'^Donate4$', views.donate4_view, name='donate4'),

    url(r'^Donate1$', views.donate1_view, name='donate1'),

    url(r'^Home$', views.home_view, name='home'),

    url(r'^About$', views.about_view, name='about'),

    url(r'^Earthquake$', views.earth_view, name='earthquake'),

    url(r'^Flood$', views.flood_view, name='flood'),

    url(r'^Drought$', views.drth_view, name='drought'),

    url(r'^Landslide$', views.land_view, name='landslide'),

    url(r'^ThankYou$', views.thankyou_view, name='thankyou'),
]

first_app/models.py
from django.db import models


# Create your models here.

class Person(models.Model):
    name = models.CharField(max_length=100)

first_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


def index(request):
    my_dict = {'insert_me': 'Hello , Now I am from first_app -  index.html !'}
    return render(request, 'first_app/index.html', context=my_dict)


def home_view(request):
    return render(request, 'first_app/home.html')


def about_view(request):
    return render(request, 'first_app/about.html')


def earth_view(request):
    return render(request, 'first_app/earthquake.html')


def flood_view(request):
    return render(request, 'first_app/flood.html')


def drth_view(request):
    return render(request, 'first_app/drought.html')


def land_view(request):
    return render(request, 'first_app/landslide.html')


def thankyou_view(request):
    return render(request, 'first_app/thankyou.html')


def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            # login the user
            login(request, user)
            return redirect('first_app:home')
    else:
        form = UserCreationForm()
    return render(request, 'first_app/registration_form.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('first_app:home')
    else:
        form = AuthenticationForm()
    return render(request, 'first_app/login_form.html', {'form': form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('first_app:login')


def donate_view(request):
    if request.method == 'GET':
        return redirect('first_app:earthquake')


def donate2_view(request):
    if request.method == 'GET':
        return redirect('first_app:flood')


def donate3_view(request):
    if request.method == 'GET':
        return redirect('first_app:drought')


def donate4_view(request):
    if request.method == 'GET':
        return redirect('first_app:landslide')


def donate1_view(request):
    if request.method == 'GET':
        return redirect('first_app:thankyou')

templates/first_app/about.html
{% extends 'first_app\base.html' %}
{% load static %}
{% block body %}
	<div class="jumbotron">
    <h1>ABOUT THE PROJECT AND IT'S MAKERS</h1>
      </div>
<DIV class="details">
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum. </p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

</DIV>

<div class="row">

  <div class="col-lg-6">
    <div class="card">
  <img src="{% static 'images\female_avatar.png' %}" alt="Avatar" style="width:100%">
  <div class="container">
    <h4><b>NIHARIKA </b></h4>
    <p>ROLL 18</p>
  </div>
</div>
  </div>

  <div class="col-lg-6">
    <div class="card">
  <img src="{% static 'images\img_avatar.png' %}" alt="Avatar" style="width:100%">
  <div class="container">
    <h4><b>SNEH </b></h4>
    <p>ROLL 05</p>
  </div>
</div>
  </div>

  <div class="col-lg-6">
    <div class="card">
  <img src="{% static 'images\img_avatar.png' %}" alt="Avatar" style="width:100%">
  <div class="container">
    <h4><b>YASHODEEP </b></h4>
    <p>ROLL 20</p>
  </div>
</div>
  </div>

  <div class="col-lg-6">
    <div class="card">
  <img src="{% static 'images\img_avatar.png' %}" alt="Avatar" style="width:100%">
  <div class="container">
    <h4><b>VIREN </b></h4>
    <p>ROLL 12</p>
  </div>
</div>
  </div>
</div>
{% endblock %}

templates/first_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>HANDFORHAND</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script src="https://kit.fontawesome.com/d371356579.js" crossorigin="anonymous"></script>
        <link rel="stylesheet" href='{% static "css\disaster.css" %}'/>
        <link rel="stylesheet" href='{% static "css\about.css" %}'/>
        <link rel="stylesheet" href='{% static "css\home.css" %}'/>
        <link rel="stylesheet" href='{% static "css\site.css" %}'/>
</head>
<body>

    <!-- Nav-Bar -->
     <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-info">
        <div class="container">
            <a class="navbar-brand" href="#"><i class="fas fa-love"></i> HandForHand</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
               <ul class="navbar-nav mr-auto">
               </ul>

              <ul class="navbar-nav navbar-right">
                  {% if user.is_authenticated %}
                 <li class="nav-item">
            <a class="nav-link" href="{% url 'first_app:home' %}">Home <span class="sr-only">(current)</span></a>
          </li>
                  <li class="nav-item">
            <form action="{% url 'first_app:logout' %}" class="nav-link" method="post">
              {% csrf_token %}
              <button type="submit">Log-Out</button>
            </form>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'first_app:about' %}">About</a>
          </li>
           {% else %}
                  <li class="nav-item">
            <a class="nav-link" href="{% url 'first_app:home' %}">Home <i class="fas fa-home"></i></a>
          </li>
            <li class="nav-item"><a class="nav-link" href="{% url 'first_app:login' %}">LogIn <i class="fas fa-user"></i></a></li>
             <li class="nav-item"><a class="nav-link" href="{% url 'first_app:register' %}">SignUp <i class="fas fa-user-plus"></i></a></li>
                  <li class="nav-item">
            <a class="nav-link" href="{% url 'first_app:about' %}">About</a>
          </li>
           {% endif %}
              </ul>
              </div>
        </div>
    </nav>
{% block body %}
{% endblock %}

  <!-- Footer -->
  <footer class="page-footer font-small blue bg-info fixed-bottom">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3 d">© 2020 Copyright:  Let's Learn!</div>

  </footer>
<!-- Footer -->


<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>


</body>
</html>

templates/first_app/drought.html
{% extends 'first_app\base.html' %}
{% load static %}
{% block body %}
    <div class="head">
    <h1>Drought Care</h1>
    </div>

    <div class="detail">
        <div class=".trans">
            <h2>Details</h2>
            <p>A drought or drouth is an event of prolonged shortages in the water supply, whether atmospheric, surface water or ground water. A drought can last for months or years, or may be declared after as few as 15 days.
            The lack of adequate precipitation, either rain or snow, can cause reduced soil moisture or groundwater, diminished stream flow, crop damage, and a general water shortage.
            </p>
        </div>
    </div>

    <div class="donate">
        <h2>Donate</h2>
        <label>Enter name </label>
        <input type="textbox" name="name">
        <p>
        <label>Enter your appropiate Amount in the box</label>
        <input type="textbox" name="money" >
        </p>
  <p><form action="{% url 'first_app:donate1' %}" class="donate-link" method="get">
              <button type="submit">Donate</button>
    </form>
  </p>
    </div>
{% endblock %}

templates/first_app/earthquake.html
{% extends 'first_app\base.html' %}
{% load static %}
{% block body %}
    <div class="head">
    <h1>Earthquake Care</h1>
    </div>

    <div class="detail">
        <div class=".trans">
            <h2>Details</h2>
            <p>An earthquake (also known as a quake, tremor or temblor) is the shaking of the surface of the Earth resulting from a sudden release of energy in the Earth's lithosphere that creates seismic waves.
            Earthquakes can range in size from those that are so weak that they cannot be felt to those violent enough to propel objects and people into the air, and wreak destruction across entire cities.
            The seismicity, or seismic activity, of an area is the frequency, type, and size of earthquakes experienced over a period of time.
            The word tremor is also used for non-earthquake seismic rumbling.</p>
        </div>
    </div>

    <div class="donate">
        <h2>Donate</h2>
        <label>Enter name </label>
        <input type="textbox" name="name">
        <p>
        <label>Enter your appropiate Amount in the box</label>
        <input type="textbox" name="money" >
        </p>
  <p><form action="{% url 'first_app:donate1' %}" class="donate-link" method="get">
              <button type="submit">Donate</button>
    </form>
  </p>
    </div>
{% endblock %}

templates/first_app/flood.html
{% extends 'first_app\base.html' %}
{% load static %}
{% block body %}
    <div class="head">
    <h1>Flood Care</h1>
    </div>

    <div class="detail">
        <div class=".trans">
            <h2>Details</h2>
            <p>Floods are the most frequent type of natural disaster and occur when an overflow of water submerges land that is usually dry. Floods are often caused by heavy rainfall,
                rapid snowmelt or a storm surge from a tropical cyclone or tsunami in coastal areas. In the sense of "flowing water", the word may also be applied to the inflow of the tide. Floods are an area of study of the discipline hydrology and are of significant concern in agriculture, civil engineering and public health.
            </p>
        </div>
    </div>

    <div class="donate">
        <h2>Donate</h2>
        <label>Enter name </label>
        <input type="textbox" name="name">
        <p>
        <label>Enter your appropiate Amount in the box</label>
        <input type="textbox" name="money" >
        </p>
  <p><form action="{% url 'first_app:donate1' %}" class="donate-link" method="get">
              <button type="submit">Donate</button>
    </form>
  </p>
    </div>
{% endblock %}

templates/first_app/form-template.html
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

   <div class="row">
    <div class="col s12 m6 z">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Log-In</span>
        </div>
          {% for field in form %}
          <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
        {% endfor %}
        <div class="card-action">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
      </div>
    </div>
  </div>


        <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

templates/first_app/home.html
{% extends 'first_app\base.html' %}
{% load static %}
{% block body %}
    <div class="jumbotron">
      <h1>परोपकारार्थं इदं बुद्धी | ब्रह्मज्ञानर्थं जीवनम् ||</h1>
      <h4>one reaches supreme knowledge through service to others</h4>
    </div>

<div class="row">
  <div class="col-lg-6">
    <div class="card"><div class="card">
  <img src="{% static 'images\flood.jpg' %}" alt="flood" style="width:100%">
  <h1>Flood Care</h1>
  <p class="price">Your small help could make a huge difference in someone's life ... we think so .. do you ?</p>
  <p><form action="{% url 'first_app:donate2' %}" class="donate-link" method="get">
              <button type="submit">Donate</button>
    </form>
  </p>
</div></div>
  </div>

  <div class="col-lg-6">
    <div class="card"><div class="card">
  <img src="{% static 'images\landslide.jpg' %}" alt="landslide" style="width:100%">
  <h1>Landslide Care</h1>
  <p class="price">Your small help could make a huge difference in someone's life ... we think so .. do you ?</p>
  <p><form action="{% url 'first_app:donate4' %}" class="donate-link" method="get">
              <button type="submit">Donate</button>
    </form>
  </p>
</div></div>
  </div>

</div>

<div class="row">

<div class="col-lg-6">
    <div class="card"><div class="card">
  <img src="{% static 'images\drought.jpg' %}" alt="drought" style="width:100%">
  <h1>Drought Care</h1>
  <p class="price">Your small help could make a huge difference in someone's life ... we think so .. do you ?</p>
  <p><form action="{% url 'first_app:donate3' %}" class="donate-link" method="get">
              <button type="submit">Donate</button>
    </form>
  </p>
</div></div>
  </div>

  <div class="col-lg-6">
    <div class="card"><div class="card">
  <img src="{% static 'images\earthquake.jpg' %}" alt="earthquake" style="width:100%">
  <h1>Earthquake Care</h1>
  <p class="price">Your small help could make a huge difference in someone's life ... we think so .. do you ?</p>
  <p><form action="{% url 'first_app:donate' %}" class="donate-link" method="get">
              <button type="submit">Donate</button>
    </form>
  </p>
</div></div>
  </div>
</div>

{% endblock %}

templates/first_app/index.html
{% extends 'first_app\base.html' %}
{% load static %}
{% block body %}
<div class="jumbotron">
  <h1 class="display-4">HAND FOR HAND</h1>
      <hr class="my-4">
    <h2>अष्टादश पुराणेषु व्यासस्य वचनद्वयम् | परोपकारः पुण्याय पापाय परपीडनम् ||</h2>

    <h4>The essence of eighteen puranas by sage Vyasa is in following two sentences, To help others is a good merit, and to trouble (or hurt) others is a sin</h4>
</div>

<!-- Carousel -->
<!--    <div class="container">-->
<!--    <div id="demo car" class="carousel slide" data-ride="carousel">-->
<!--      <ul class="carousel-indicators">-->
<!--        <li data-target="#demo" data-slide-to="0" class="active"></li>-->
<!--        <li data-target="#demo" data-slide-to="1"></li>-->
<!--        <li data-target="#demo" data-slide-to="2"></li>-->
<!--        <li data-target="#demo" data-slide-to="3"></li>-->
<!--      </ul>-->

<!--<div class="carousel-inner">-->
<!--        <div class="carousel-item active">-->
<!--          <img src="https://images.unsplash.com/photo-1519071711965-f84a1482a05e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&h=900&q=50" alt="Los Angeles" width="100%" height="500">-->
<!--          <div class="carousel-caption">-->
<!--            <h3>BushFire</h3>-->
<!--          </div>-->
<!--        </div>-->
<!--        <div class="carousel-item">-->
<!--          <img src="https://images.unsplash.com/photo-1551006097-61dd4a01d3e6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&h=900&q=50" alt="Chicago" width="100%" height="500">-->
<!--          <div class="carousel-caption">-->
<!--            <h3>Wild-BushFire</h3>-->
<!--          </div>-->
<!--        <div class="carousel-item">-->
<!--          <img src="https://images.unsplash.com/photo-1561481292-5a283556c849?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&h=900&q=50" alt="Chicago" width="100%" height="500">-->
<!--          <div class="carousel-caption">-->
<!--            <h3>EarthQuake</h3>-->
<!--          </div>-->
<!--        </div>-->
<!--       <div class="carousel-item">-->
<!--          <img src="https://images.unsplash.com/photo-1547683905-f686c993aae5?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&h=900&q=50" alt="Chicago" width="100%" height="500">-->
<!--          <div class="carousel-caption">-->
<!--            <h3>Floods</h3>-->
<!--          </div>-->
<!--        </div>-->
<!--      <a class="carousel-control-prev" href="#demo" data-slide="prev">-->
<!--        <span class="carousel-control-prev-icon"></span>-->
<!--      </a>-->
<!--      <a class="carousel-control-next" href="#demo" data-slide="next">-->
<!--        <span class="carousel-control-next-icon"></span>-->
<!--      </a>-->
<!--    </div>-->
<!--  </div>-->
{% endblock %}

templates/first_app/landslide.html
{% extends 'first_app\base.html' %}
{% load static %}
{% block body %}
    <div class="head">
    <h1>Landslide Care</h1>
    </div>

    <div class="detail">
        <div class=".trans">
            <h2>Details</h2>
            <p>A landslide is the movement of rock, earth, or debris down a sloped section of land. Landslides are caused by rain, earthquakes, volcanoes, or other factors that make the slope unstable. Geologists, scientists who study the physical formations of the Earth, sometimes describe landslides as one type of mass wasting.
               The term landslide or less frequently, landslip, refers to several forms of mass wasting that include a wide range of ground movements, such as rockfalls, deep-seated slope failures, mudflows, and debris flows.
            </p>
        </div>
    </div>

    <div class="donate">
        <h2>Donate</h2>
        <label>Enter name </label>
        <input type="textbox" name="name">
        <p>
        <label>Enter your appropiate Amount in the box</label>
        <input type="textbox" name="money" >
        </p>
  <p><form action="{% url 'first_app:donate1' %}" class="donate-link" method="get">
              <button type="submit">Donate</button>
    </form>
  </p>
    </div>
{% endblock %}

templates/first_app/login_form.html
{% extends 'first_app\base.html' %}
{% load static %}
{% block body %}
<div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'first_app\form-template.html' %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/first_app/registration_form.html
{% extends 'first_app\base.html' %}
{% load static %}
{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'first_app\signup-temp.html' %}
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/first_app/signup-temp.html
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

   <div class="row">
    <div class="col s12 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title">Sign-Up</span>
        </div>
          {% for field in form %}
          <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
        {% endfor %}
        <div class="card-action">
            <button type="submit" class="btn btn-success">Submit</button>
        </div>
      </div>
    </div>
  </div>


        <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

templates/first_app/thankyou.html
{% extends 'first_app\base.html' %}
{% load static %}
{% block body %}
<div class="fgh">THANK YOU</div>
{% endblock %}